from __future__ import annotations

from typing import Callable, List, Optional, TYPE_CHECKING

from engine.order import Order, OrderType, Side, Trade
from engine.orderbook import OrderBook

if TYPE_CHECKING:
    from engine.redis_state import RedisStateManager


class MatchingEngine:
    """
    Accepts incoming orders, matches them against the order book using
    price-time priority, and emits Trade objects for each execution.

    Limit orders that cross the opposite side are matched immediately.
    Any unfilled remainder rests on the book. Market orders aggress
    the opposite side and are cancelled if the book is exhausted.
    """

    def __init__(
        self,
        book: Optional[OrderBook] = None,
        on_trade: Optional[Callable[[Trade], None]] = None,
        redis_state: Optional["RedisStateManager"] = None,
    ) -> None:
        self._book = book or OrderBook()
        self._trades: List[Trade] = []
        self._on_trade = on_trade
        self._redis = redis_state

    def submit_order(self, order: Order) -> List[Trade]:
        """
        Submit an order to the engine.

        For limit orders: match against the opposite side if the price
        crosses, then place any unfilled remainder on the book.

        For market orders: match against the opposite side until filled
        or the book is exhausted. Remaining quantity is cancelled (market
        orders never rest on the book).

        Returns a list of Trade objects generated by this submission.
        """
        trades = self._match(order)

        if order.remaining > 0:
            if order.order_type == OrderType.LIMIT:
                self._book.add_order(order)
                if self._redis:
                    self._redis.save_order(order)
            else:
                order.cancel()
                if self._redis:
                    self._redis.update_order(order)

        return trades

    def _match(self, order: Order) -> List[Trade]:
        """
        Inner matching loop — the hot path of the engine.

        Walks the opposite side of the book, executing trades at the
        resting order's price until the incoming order is filled or
        no more matchable levels exist.
        """
        trades: List[Trade] = []

        while order.remaining > 0:
            if order.side == Side.BUY:
                best = self._book.best_ask()
            else:
                best = self._book.best_bid()

            if best is None:
                break

            if order.order_type == OrderType.LIMIT:
                if order.side == Side.BUY and order.price < best.price:
                    break
                if order.side == Side.SELL and order.price > best.price:
                    break

            fill_qty = min(order.remaining, best.remaining)
            exec_price = best.price

            order.fill(fill_qty)
            best.fill(fill_qty)

            if order.side == Side.BUY:
                trade = Trade(
                    buy_order_id=order.order_id,
                    sell_order_id=best.order_id,
                    price=exec_price,
                    quantity=fill_qty,
                )
            else:
                trade = Trade(
                    buy_order_id=best.order_id,
                    sell_order_id=order.order_id,
                    price=exec_price,
                    quantity=fill_qty,
                )

            trades.append(trade)
            self._trades.append(trade)

            if self._redis:
                self._redis.update_order(order)
                self._redis.update_order(best)
                self._redis.save_trade(trade)

            if self._on_trade:
                self._on_trade(trade)

        return trades

    def cancel_order(self, order_id: str) -> Order:
        """
        Cancel an order by ID. Delegates to the underlying OrderBook.

        Returns the cancelled Order. Raises KeyError if not found,
        ValueError if already filled.
        """
        order = self._book.cancel_order(order_id)
        if self._redis:
            self._redis.update_order(order)
        return order

    def get_order(self, order_id: str) -> Optional[Order]:
        """Look up an order by ID. Returns None if not found."""
        return self._book.get_order(order_id)

    def snapshot(self, recent_trade_count: int = 20) -> dict:
        """
        Return the current state of the book and recent trade activity.

        Extends the OrderBook snapshot with:
            - total_trades: total number of trades executed
            - recent_trades: last N trades as dicts
        """
        snap = self._book.snapshot()
        snap["total_trades"] = len(self._trades)

        recent_trades = []
        for t in self._trades[-recent_trade_count:]:
            recent_trades.append({
                "trade_id": t.trade_id,
                "buy_order_id": t.buy_order_id,
                "sell_order_id": t.sell_order_id,
                "price": t.price,
                "quantity": t.quantity,
                "timestamp": t.timestamp,
            })
        snap["recent_trades"] = recent_trades

        return snap

    def flush(self) -> None:
        """Clear all orders and trades. syncs with Redis if connected."""
        self._book.flush()
        self._trades = []
        if self._redis:
            self._redis.flush()

